import {
  HomeModernIcon,
  FireIcon,
  WifiIcon,
  SparklesIcon,
  WrenchScrewdriverIcon,
  BoltIcon,
  KeyIcon,
  TvIcon,
  BeakerIcon,
  ShieldCheckIcon,
  DevicePhoneMobileIcon,
  GlobeAltIcon,
  ArrowTrendingUpIcon,
  EyeIcon,
  SunIcon,
  BuildingOffice2Icon,
  TruckIcon,
  BuildingLibraryIcon,
  UserGroupIcon,
  GiftIcon,
  CameraIcon,
  ArrowsPointingOutIcon,
  WrenchIcon,
  BuildingStorefrontIcon,
  ChatBubbleBottomCenterTextIcon,
  ArrowPathRoundedSquareIcon,
  ChartBarIcon,
  PuzzlePieceIcon,
  ClockIcon,
  PresentationChartLineIcon,
  UsersIcon,
} from "@heroicons/react/24/outline";

export type AmenityItem = {
  item: string;
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
};

export const allAmenities: AmenityItem[] = [
  { item: "Swimming Pool", icon: SparklesIcon },
  { item: "Gym", icon: BoltIcon },
  { item: "Garden", icon: GlobeAltIcon },
  { item: "Air Conditioning", icon: SunIcon },
  { item: "Balcony", icon: EyeIcon },
  { item: "Fireplace", icon: FireIcon },
  { item: "Washer/Dryer", icon: WrenchScrewdriverIcon },
  { item: "Dishwasher", icon: BeakerIcon },
  { item: "Microwave", icon: BoltIcon },
  { item: "Refrigerator", icon: TvIcon },
  { item: "Elevator", icon: ArrowsPointingOutIcon },
  { item: "Pet Friendly", icon: UserGroupIcon },
  { item: "Furnished", icon: GiftIcon },
  { item: "Wi-Fi", icon: WifiIcon },
  { item: "Security System", icon: ShieldCheckIcon },
  { item: "Storage", icon: BuildingStorefrontIcon },
  { item: "Hot Tub", icon: BeakerIcon },
  { item: "Sauna", icon: FireIcon },
  { item: "Outdoor BBQ Area", icon: FireIcon },
  { item: "Guest House", icon: HomeModernIcon },
  { item: "Home Theater", icon: TvIcon },
  { item: "Smart Home Features", icon: DevicePhoneMobileIcon },
  { item: "Private Beach Access", icon: GlobeAltIcon },
  { item: "Walk-in Closet", icon: ArrowPathRoundedSquareIcon },
  { item: "Granite Countertops", icon: ChartBarIcon },
  { item: "Hardwood Floors", icon: BuildingLibraryIcon },
  // { item: "Ceiling Fans", icon: FanIcon },
  { item: "Waterfront", icon: GlobeAltIcon },
  { item: "Mountain View", icon: EyeIcon },
  { item: "City View", icon: BuildingOffice2Icon },
  { item: "Double Glazed Windows", icon: BuildingOffice2Icon },
  { item: "Electric Vehicle Charging Station", icon: TruckIcon },
  { item: "Game Room", icon: PuzzlePieceIcon },
  { item: "On-site Maintenance", icon: WrenchIcon },
  { item: "24/7 Concierge Service", icon: UsersIcon },
  { item: "Business Center", icon: PresentationChartLineIcon },
  { item: "Clubhouse", icon: BuildingLibraryIcon },
];

export const getAmenity = (name: string): AmenityItem | undefined =>
  allAmenities.find((amenity) => amenity.item === name);